Models/ViewModels/TablaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCCrud.Models.ViewModels
{
    public class TablaViewModel
    {
        private int id;
        private string nombre;
        private string correo;
        private DateTime fecha_nacimiento;

        public int Id { get => id; set => id = value; }
        public string Nombre { get => nombre; set => nombre = value; }
        public string Correo { get => correo; set => correo = value; }
        public DateTime Fecha_nacimiento { get => fecha_nacimiento; set => fecha_nacimiento = value; }
    }
}

Models/tabla.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    }
}

Controllers/TablaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCCrud.Models;
using MVCCrud.Models.ViewModels;

namespace MVCCrud.Controllers
{
    public class TablaController : Controller
    {
        // GET: Tabla
        public ActionResult Index()
        {
            List<TablaViewModel> list = new List<TablaViewModel>();
            using (CrudEntities db = new CrudEntities())
            {
                list = (from d in db.tabla
                            select new TablaViewModel
                            {
                                Id = d.id,
                                Nombre = d.nombre,
                                Correo = d.correo,
                                Fecha_nacimiento = (DateTime)d.fecha_nacimiento
                            }).ToList();
            }
                return View(list);
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(NuevoTablaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (CrudEntities db = new CrudEntities())
                    {
                        var oTabla = new tabla();
                        oTabla.correo = model.Correo;
                        oTabla.nombre = model.Nombre;
                        oTabla.fecha_nacimiento = model.Fecha_nacimiento;
                        db.tabla.Add(oTabla);
                        db.SaveChanges();

                    }

                    return Redirect("/tabla");
                }

                return View(model);

                
            }
            catch (Exception ex)
            {
                 
                throw new Exception(ex.Message);
            }
        }

        
        public ActionResult Editar(int id)
        {
            NuevoTablaViewModel model = new NuevoTablaViewModel();
            using (CrudEntities db = new CrudEntities())
            {
                var oTabla = db.tabla.Find(id);
                model.Nombre = oTabla.nombre;
                model.Correo = oTabla.correo;
                model.Fecha_nacimiento = (DateTime)oTabla.fecha_nacimiento;
                model.Id = oTabla.id;
            }

                return View(model);
        }

        [HttpPost]
        public ActionResult Editar(NuevoTablaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (CrudEntities db = new CrudEntities())
                    {
                        var oTabla = db.tabla.Find(model.Id);
                        oTabla.correo = model.Correo;
                        oTabla.nombre = model.Nombre;
                        oTabla.fecha_nacimiento = model.Fecha_nacimiento;
                        db.Entry(oTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();

                    }

                    return Redirect("/tabla");
                }

                return View(model);


            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {

            using (CrudEntities db = new CrudEntities())
            {
                var oTabla = db.tabla.Find(id);
                db.tabla.Remove(oTabla);
                db.SaveChanges();
            }

            return Redirect("/tabla");
        }


    }
}

Views/Tabla/Editar.cshtml
@model MVCCrud.Models.ViewModels.NuevoTablaViewModel
@using System.Web.Mvc

@{ ViewBag.Title = "Editar"; }

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
</head>

<body>
    <div class="container">
        <h2 class="mt-3">@ViewBag.Title</h2>

        @using (Html.BeginForm("Editar", "Tabla", FormMethod.Post))
        {
            @Html.HiddenFor(d=> d.Id)
<div class="form-group">
    @Html.LabelFor(d => d.Nombre)
    @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
    @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "danger" })
</div>

                <div class="form-group">
                    @Html.LabelFor(d => d.Correo)
                    @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "danger" })
                </div>

                                <div class="form-group">
                                    @Html.LabelFor(d => d.Fecha_nacimiento) <br />
                                    @Html.EditorFor(d => d.Fecha_nacimiento, "", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.Fecha_nacimiento, null, new { @class = "danger" })
                                </div><br />
                                                <div style="text-align:right">
                                                    <input value="Guardar" type="submit" class="btn btn-primary" />
                                                </div>}
    </div>

    <script>
        $(document).ready(function () {
            $('.datetimepicker').datetimepicker({
                timepicker: false,
                format: 'd/m/Y'
            });
        });</script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmIaPsmFyJdL8jIkvH3"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
</body>

Views/Tabla/Index.cshtml
@model List<MVCCrud.Models.ViewModels.TablaViewModel>
@{
    ViewBag.Title = "Mis Datos";
}

<h2>ViewBag.Title</h2>

<div class="row" style="text-align:right; padding:5px;">
    <a href="~/Tabla/Nuevo" class="btn btn-primary">Nuevo</a>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Correo</th>
                <th>Fecha de Nacimiento</th>
                <th></th>
            </tr>
            @foreach (var element in Model)
            {
        <tr>
            <td>@element.Id</td>
            <td>@element.Nombre</td>
            <td>@element.Correo</td>
            <td>@element.Fecha_nacimiento</td>
            <td>
                <a class="btn btn-default" href="~/Tabla/Editar/@element.Id">editar</a>
                <a class="btn btn-danger" href="~/Tabla/Eliminar/@element.Id">eliminar</a>
            </td>
        </tr>
            }
        </table>
    </div>

</div>

Views/Tabla/Nuevo.cshtml
@model MVCCrud.Models.ViewModels.NuevoTablaViewModel
@{ ViewBag.Title = "Nuevo"; }

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
</head>

<body>
    <div class="container">
        <h2 class="mt-3">@ViewBag.Title</h2>

        @using (Html.BeginForm("Nuevo", "Tabla", FormMethod.Post))
        {
<div class="form-group">
    @Html.LabelFor(d => d.Nombre)
    @Html.TextBoxFor(d => d.Nombre, "", new { @class="form-control" })
    @Html.ValidationMessageFor(d=> d.Nombre,null ,new {@class="danger"})
</div>

<div class="form-group">
    @Html.LabelFor(d => d.Correo)
    @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
    @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "danger" })
</div>

<div class="form-group">
    @Html.LabelFor(d => d.Fecha_nacimiento) <br />
    @Html.EditorFor(d => d.Fecha_nacimiento, "", new { @class = "form-control" })
    @Html.ValidationMessageFor(d => d.Fecha_nacimiento, null, new { @class = "danger" })
</div><br />
                                <div style="text-align:right">
                                 <input value="Guardar" type="submit" class="btn btn-primary"/>
                                </div>          
                                                
          }
    </div>

    <script>
        $(document).ready(function () {
            $('.datetimepicker').datetimepicker({
                timepicker: false,
                format: 'd/m/Y'
            });
        });
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmIaPsmFyJdL8jIkvH3"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
</body>